baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ivan Porta'
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Ivan Porta"
  description = "Microsoft Certified DevOps Engineer Expert | MCT | Public Speaker | Customer Engineer @Microsoft"
  menu_item_separator = " - "
  avatar = "/images/ivanporta.jpg"
  favicon = "`images/favicons/favicon.ico"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/GTRekter"
  [[params.social]]
    icon = "twitter"
    name = "@GTRekter"
    url = "https://twitter.com/GTRekter"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/ivanporta/"
  [[params.social]]
    icon = "medium"
    name = "Medium"
    url = "https://gtrekter.medium.com/"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"